name: Deploy xyvin-erp frontend to aws lightsail

on:
  push:
    paths:
      - "erp-frontend/**"
      - ".github/workflows/frontend.yml"
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "erp-frontend/package-lock.json"

      - name: Install Dependencies and Build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_NODE_ENV: ${{ secrets.VITE_NODE_ENV }}
          VITE_APP_NAME: ${{ secrets.VITE_APP_NAME }}
        run: |
          cd erp-frontend
          npm ci
          npm run build
          mv ./dist ../xyvin-erp-frontend

      - name: Verify SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          timeout: 60s
          script: |
            echo "SSH connection successful"
            whoami
            pwd
            ls -la

      - name: Deploy to Lightsail using rsync
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ./xyvin-erp-frontend/
          remote_path: ~/deploy-temp/
          remote_host: ${{ secrets.LIGHTSAIL_HOST }}
          remote_user: ${{ secrets.LIGHTSAIL_USER }}
          remote_key: ${{ secrets.LIGHTSAIL_KEY }}

      - name: Finalize deployment on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          timeout: 60s
          script: |
            echo "Deploying to web root..."
             sudo rm -rf /var/www/html/xyvin-erp
             sudo mkdir -p /var/www/html/xyvin-erp
             sudo cp -R ~/deploy-temp/* /var/www/html/xyvin-erp
             sudo chown -R www-data:www-data /var/www/html/xyvin-erp
             sudo chmod -R 755 /var/www/html/xyvin-erp
             sudo rm -rf ~/deploy-temp

             echo "Restarting Nginx..."
             sudo rm -rf /var/cache/nginx/*
             sudo systemctl restart nginx

             echo "Deployment completed!"
